"""one cached volume can serve several questions

Revision ID: 135bccbf473a
Revises: 36d287a01917
Create Date: 2026-09-05 19:46:14.982974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135bccbf473a'
down_revision: Union[str, None] = '36d287a01917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_documents_source_external', 'source_documents', type_='unique')
    op.create_unique_constraint('uq_source_documents_source_external', 'source_documents', ['source_key', 'external_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_documents_source_external', 'source_documents', type_='unique')
    op.create_unique_constraint('uq_source_documents_source_external', 'source_documents', ['source_key', 'external_id'])
    # ### end Alembic commands ###
