"""pgvector extension and the content pipeline source tables

Revision ID: 36d287a01917
Revises: 3ce918e2ede4
Create Date: 2026-09-05 03:52:03.964195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# The concrete pgvector type, not db.Vector. A migration is a frozen snapshot
# of the schema at this revision; importing the application's type would let a
# later change to EMBEDDING_DIM retroactively alter what this migration builds.
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '36d287a01917'
down_revision: Union[str, None] = '3ce918e2ede4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Must come first — chunk_embeddings.embedding can't be created without it.
    # IF NOT EXISTS so a database where someone enabled it by hand still
    # upgrades cleanly.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'question_id', 'published_date', name='uq_source_documents_scope_key'),
    sa.UniqueConstraint('source_key', 'external_id', name='uq_source_documents_source_external')
    )
    op.create_index(op.f('ix_source_documents_question_id'), 'source_documents', ['question_id'], unique=False)
    op.create_table('source_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id', 'question_id', 'published_date'], ['source_documents.id', 'source_documents.question_id', 'source_documents.published_date'], name='fk_source_chunks_document_scope', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_source_chunks_document_ordinal')
    )
    op.create_index('ix_source_chunks_question_published', 'source_chunks', ['question_id', 'published_date'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings')
    op.drop_index('ix_source_chunks_question_published', table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index(op.f('ix_source_documents_question_id'), table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###

    # The extension is deliberately left in place. It's database-scoped, not
    # owned by these tables, and dropping it would take out anything else that
    # had started using it.
