"""initial schema: votes and daily_questions

Revision ID: 3ce918e2ede4
Revises: 
Create Date: 2026-09-05 01:26:05.840677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce918e2ede4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_questions',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.Column('voter_id', sa.String(length=64), nullable=False),
    sa.Column('choice', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'voter_id', name='uq_votes_question_voter')
    )
    op.create_index(op.f('ix_votes_question_id'), 'votes', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_question_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_table('daily_questions')
    # ### end Alembic commands ###
