"""candidates and their review state

Revision ID: a5cc6ca06258
Revises: 135bccbf473a
Create Date: 2026-09-05 19:56:03.494513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cc6ca06258'
down_revision: Union[str, None] = '135bccbf473a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=32), nullable=False),
    sa.Column('chamber', sa.String(length=16), nullable=False),
    sa.Column('vote_date', sa.Date(), nullable=False),
    sa.Column('vote_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yea', sa.Integer(), nullable=False),
    sa.Column('nay', sa.Integer(), nullable=False),
    sa.Column('attention_percentile', sa.Float(), nullable=False),
    sa.Column('closeness', sa.Float(), nullable=False),
    sa.Column('coalition_break', sa.Float(), nullable=False),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress', 'bill_number', name='uq_candidates_bill')
    )
    op.create_index('ix_candidates_status_rank', 'candidates', ['status', 'attention_percentile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_status_rank', table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
